[package]
name = "jup-v6"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anchor-gen = { version = "0.4.0", path = "../../crates/anchor-gen" }
anchor-lang = "0.29.0"
anyhow = "1.0.79"
base58 = "*"
